site_name: HexViewer Documentation
repo_url: https://github.com/facelessuser/HexViewer
site_description: A Sublime Text hex viewer and editor.
copyright: Copyright &copy; 2011 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
- ['index.md', 'Home']
- ['usage.md', 'User Guide']
- ['license.md', 'License']
theme: readthedocs
extra_javascript:
- js/inlinehilite.js
extra_css:
- css/inlinehilite.css
markdown_extensions:
- markdown.extensions.extra
- markdown.extensions.admonition
- markdown.extensions.smarty
- pymdownx.inlinehilite(use_pygments=False)
- pymdownx.magiclink
- pymdownx.betterem
- pymdownx.tilde
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.githubemoji
- pymdownx.tasklist
- pymdownx.superfences
